# Use postgres/example user/password credentials
version: '3.1'

services:
  shopper:
    image: shopper
    restart: always
    ports:
      - 8081:8081

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  dbmaria:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080